#cloud-config

package_update: true

packages:
  - httpd
  - php
  - php-mysqlnd
  - php-fpm
  - php-mysqli
  - php-json
  - php-gd
  - mariadb105-server
  - wget

runcmd:
  - systemctl enable --now httpd
  - systemctl enable --now mariadb